### ISSUE TITLE
How to replace GPT with other LLMs, for example, GLM-4?

### ISSUE THREAD

**Issue by MathamPollard** [AuvaLab/itext2kg#1]

**Comment by vigorous2008** [comment]
I have the same question.

**Comment by aceliuchanghong** [comment]
*3

**Comment by lairgiyassir** [comment]
Hello, 

It's a great feature to include! 

To run iText2KG, you'll need both an LLM and an embedding model. 

We've hardcoded ChatOpenAI with OpenAIEmbeddings models, as our article is based on these. 
However, since we're utilizing the LangChain output parser, you can use any LLM model that LangChain supports, such as GLM-4 (see https://python.langchain.com/v0.2/docs/integrations/chat/zhipuai/). 

I will configure the LLM and embedding models as variables to allow for the flexibility to replace them with any LangChain-integrated model.

Thank you :)

**Comment by redpintings** [comment]
If it could support more local models or other APIs such as GLM or Deepseek, it would be a great project

**Comment by chrisbraddock** [comment]
> I will configure the LLM and embedding models as variables to allow for the flexibility to replace them with any LangChain-integrated model.

Separate vars for URLs/models for both encoding and inference would be killer.
