### ISSUE TITLE
unresolved (false positive) entities

### ISSUE THREAD

**Issue by fireSunset** [AuvaLab/itext2kg#20]
I have encountered some difficulties while reading your literature and was hoping to receive your guidance. Thank you very much for your time and assistance. In the experimental section of the article, it refers to "extracted triplets. – Entity/Relation Resolution False Discovery Rate: Assessing the ratio of unresolved (false positive) entities or relations to the overall number of extracted entities or relations." The term "unresolved (false positive) entities" pertains to what exactly, and how is it determined that an entity is a false positive?

**Comment by lairgiyassir** [comment]
My pleasure, 

To understand the False Discovery Rate of Unresolved Entities. Let's take the following basic example, 

* Input Text:
"Amazon Web Services (AWS) announced new cloud solutions. AWS aims to revolutionize cloud computing."

* Extracted Entities:

- Cloud Solutions
- Amazon Web Services
- AWS
- Cloud Computing

--

As you can see, AWS and Amazon Web Services are two unresolved entities from the extracted entities list : 

the false discovery rate = 2/4

**Comment by fireSunset** [comment]
This means that the two forms of the same expression have not been unified into one expression, so these two entities are Unresolved Entities.  I'm not sure if my understanding is accurate now=v=

**Comment by lairgiyassir** [comment]
Yes exactly! 

Unresolved entities refer to situations where multiple mentions of the same concept or entity are not recognized as referring to the same entity, leading to inconsistencies in knowledge graph construction. 
This issue arises because names or references may vary slightly across contexts (semantic blocks), creating ambiguity for automatic systems attempting to resolve them.

Examples of Unresolved Entities:
- Person Names:
"John Smith" in one document and "J. Smith" in another might refer to the same person but are not resolved correctly, appearing as two separate entities.
- Organization Names:
"International Business Machines" vs. "IBM" might be treated as two distinct entities even though they refer to the same organization.
- Locations:
"New York City" vs. "NYC" could remain unresolved, leading to redundant nodes in the knowledge graph.
- Concepts with Synonyms:
A system may fail to resolve "bike" and "bicycle" as the same entity, leading to duplicated nodes in the graph for a single concept.

**Comment by fireSunset** [comment]
Thank you for your response. I have one last small question. Are the evaluation metrics mentioned in the article, such as Triplet Extraction Precision and Entity/Relation Resolution False Discovery Rate, assessed manually? I feel that large models may not be accurate enough in determining relevance and whether they point to the same concept ❤ =v= ❤

**Comment by lairgiyassir** [comment]
Feel free to ask any question about iText2KG :) 

Exactly! 
After generating the KG with the different baseline methods, you check manually how much unresolved entities/relations you have in each list of entities/relations.
