### ISSUE TITLE
too many isolated entities

### ISSUE THREAD

**Issue by KannamSridharKumar** [AuvaLab/itext2kg#4]
I ran the example notebook using one of the CVs provided. I've used the CV pydantic model provided in the utilities. 

When I visualise the final results, I see a number of isolated entities. For example, the person Emily is connected to only Linkedin with relationship "has linkdein", Emily is not connected to / or have relationship with any other entities. 

Can you pls share you code which has produced the results shown in the image where your results are compared with 2 other frameworks. 

Thanks,

**Comment by lairgiyassir** [comment]
Hi KannamSridharKumar,

Thank you for pointing out this issue.

The isolated entities are primarily caused by LLM hallucinations when the context provided with the entities does not contain sufficient information about them. For example, in the case of a CV, the values in the distilled JSON are already concepts (rather than rich texts), so when combined with the key, the semantic block does not provide enough information about the entity. For the first semantic block, "name - Emily Davis," the entity is Emily Davis. Still, even if we re-prompt the LLM, it may not be able to extract relationships because the context is too limited or lacks sufficient information about the entity.

You have three options to handle this:

**1. Write a function that transforms the distilled JSON into a graph with entities and relationships without using LLMs:**
In cases where the values of the distilled JSON are already concepts and not full texts, you can write a function that converts the distilled JSON, consisting of keys and values, into a graph. The relationships will be derived from the keys; the same applies to the node type. You only need to add embeddings as properties to the nodes. 
This approach is beneficial because it does not require an LLM.

**2. The second solution _(what we did)_: pass all the distilled JSON as a semantic block to iText2KG.**
To help the LLM understand the global context of the CV, you can pass all the distilled JSON to iText2KG, but ensure that you replace "{" and "}" with "[" and "]" to avoid query errors.

**3. The third solution: pass the original chunks to iText2KG without the document distiller.**
As mentioned in the article, we observed that for less unstructured documents (like a CV), the document distiller does not significantly improve KG construction because the document already contains information in a relatively structured format.
Therefore, you can pass the chunks to iText2KG without using the document distiller (but you may have some noise).

PS:
You can combine these methods depending on the use case. For example, for a scientific article, you might choose to add the value of the "title" key directly to the graph without using iText2KG and pass only text-rich values, such as the abstract, key findings, etc.

You can use the following notebook to reconduct the obtained CV graph : https://colab.research.google.com/drive/1IKVVGARM3OgLAvEivj71NyapF-VMay06?usp=sharing

I have reconducted this graph for Emily's CV. 
![cv to graph](https://github.com/user-attachments/assets/961a64a3-d864-42aa-8a58-6fb6758b49e9)
![cv to graph](https://github.com/user-attachments/assets/961a64a3-d864-42aa-8a58-6fb6758b49e9)

**Comment by KannamSridharKumar** [comment]
Thanks for sharing the code and insights. The only difference between your code and mine is this line

Mine:
itext2kg.build_graph(sections=semantic_blocks)

Your code:
itext2kg.build_graph(sections=[semantic_blocks])

For the scientific article example provided, the [] are not used. Not using the [] passing the semantic_blocks with too little info to the LLM. For example, only name, only phone number etc are passed to the LLM. 

Thanks,
