### ISSUE TITLE
What is "distilled_doc"  in different_llm_models.ipynb of examples

### ISSUE THREAD

**Issue by Tanguosen** [AuvaLab/itext2kg#6]
![屏幕截图 2024-09-19 211009](https://github.com/user-attachments/assets/058ffb89-a8d6-4931-a398-18d8eb3eb965)

**I cant find it in code anywhere，but I find it in github homepage** 

![image](https://github.com/user-attachments/assets/f245c330-810c-4029-8b84-43988d90b4bf)

**Do I need to parse a few documents on my own?**

**Comment by lairgiyassir** [comment]
Hello, 

Thank you for reporting this bug. 
You are right, distilled_doc should be renamed distilled_cv.

Tell me if this resolves the issue.

**Comment by Tanguosen** [comment]
Thanks！This problem has been solved, but new problems have arisen：
![image](https://github.com/user-attachments/assets/c8ef4005-a258-4dc5-b402-4a8de7c972e4)

**Comment by lairgiyassir** [comment]
Thank you for reporting that!

Which LLM model are you using? 
The problem is that your LLM could not parse the output in the desired format.

**Comment by Tanguosen** [comment]
Having used llama3.1:8b and qwen2:7b, maybe the 70B model should be used, or maybe the model context length is not long enough to output something.

**Comment by lairgiyassir** [comment]
Yeah maybe. 
In the future upgrade, I will try to prompt the LLM to force it to format the output in the desired format. 

However, if the cell "Document Distiller" has passed, this means that the model formatted the output successfully for document distillation.

Could you please share with me what is inside the semantic_blocks_cv variable?

**Comment by Tanguosen** [comment]
![image](https://github.com/user-attachments/assets/c239bf56-5c41-4a52-b5ff-b70c8520a26f)
This is running with llama3.1:8b
But I changed the context length of ollama's default 2048 to 20480：
![image](https://github.com/user-attachments/assets/3fa748d2-f3d4-468e-bef5-891156174091)
It seems to have succeeded

**Comment by lairgiyassir** [comment]
Yeah good, 

semantic_blocks_cv should be as shown in the **2nd image.** 
Could you retry building the graph? 

and could you tell me if it passed?

**Comment by Tanguosen** [comment]
![image](https://github.com/user-attachments/assets/aecff4e5-3220-4a76-9eb7-f787316cc495)
Mention a blank entity { 'label': '', 'name': '' }. This means that no entity is recognized, but when I look at the sections variable：
![image](https://github.com/user-attachments/assets/bef0d0cc-4e90-409c-8812-6a256660eaea)

**Comment by lairgiyassir** [comment]
Is there a way to upgrade llama3.1 8b to 70b? 

1. Could you re-run the cell to see if you have the same problem?
2. Could you please substitute "semantic_blocks_cv" with the term "semantic_blocks_cv" (excluding the brackets)? We aim to transmit the semantic blocks individually rather than all together due to the context window limitation.

**Comment by Tanguosen** [comment]
![image](https://github.com/user-attachments/assets/c90e1336-2a8c-4cc4-bfc1-803ee1dbabdc)
Can you tell me how to access ollama on the server, my local computer is 4070s, I can't run the 70b model, but the server has two A100 graphics cards.

**Comment by lairgiyassir** [comment]
It could not structure the output, unfortunately :(. 

Full tutorial here: https://python.langchain.com/v0.2/docs/integrations/chat/ollama/
You need just to download it to the server. 
If you have Linux, download it using 

`curl -fsSL https://ollama.com/install.sh | sh`

link: https://ollama.com/download/linux

**Comment by Tanguosen** [comment]
I successfully ran all the code and generated neo4j, using qwen2.5:7b and I deleted most of the resume (due to context limitations)
If it's a long text scenario, do you plan to chunk the text like RAG in the future?

**Comment by lairgiyassir** [comment]
Hello,

Great news! Thank you for the update.

I find it odd that you deleted all the resume information because is not too long. Do you mean you deleted the info from the resume for the Document Distiller?

Because the distilled CV (the document we got from the Document Distiller) isn’t too long.

In any case, you can try chunking the document into sections either before running it through the Document Distiller or before building the graph with iText2KG. You can use some text splitters provided by Langchain: https://python.langchain.com/v0.1/docs/modules/data_connection/document_transformers/

Please let me know if you succeed in chunking the document and passing it to either the Document Distiller or iText2KG.
